import { randomUUID } from "node:crypto";
import type { PoolConnection } from "mariadb";
import { config } from "../../config.js";
import { inTransaction,pool } from "../../db.js";
import { coreBankingProvider } from "../../integrations/flexcube/index.js";
import { objectStorageProvider } from "../../integrations/object-storage/index.js";
import { recordAuditEvent } from "../audit/index.js";
import { getKycCase } from "../kyc/index.js";

export type OperationsAction="APPROVE"|"REJECT"|"REQUEST_MORE_INFORMATION"|"ESCALATE";
function httpError(status:number,message:string){return Object.assign(new Error(message),{status});}
export async function getOperationsDashboard(){const rows=await pool.query<any[]>(`SELECT SUM(status='PENDING_REVIEW') AS pendingKyc,SUM(DATE(submitted_at)=CURRENT_DATE) AS submittedToday,SUM(status='APPROVED' AND DATE(reviewed_at)=CURRENT_DATE) AS approvedToday,SUM(status='REJECTED') AS rejected,SUM(risk_level='HIGH') AS highRiskCustomers,SUM(status='MORE_INFORMATION_REQUIRED') AS requiringMoreInformation FROM kyc_cases`);return Object.fromEntries(Object.entries(rows[0]||{}).map(([key,value])=>[key,Number(value||0)]));}
export async function searchCustomers(input:{query?:string;status?:string;riskLevel?:string}){const query=`%${input.query||""}%`;return pool.query<any[]>(`SELECT u.id,CONCAT_WS(' ',p.first_name,p.middle_name,p.last_name) AS name,u.email,p.mobile_number AS mobileNumber,p.flexcube_customer_id AS flexcubeCustomerId,p.customer_number AS customerNumber,u.status AS digitalStatus,u.kyc_status AS kycStatus,p.kyc_level AS kycLevel,p.risk_level AS riskLevel,k.id AS caseId,k.submitted_at AS submittedAt FROM users u JOIN customer_profiles p ON p.user_id=u.id LEFT JOIN kyc_cases k ON k.customer_id=u.id AND k.id=(SELECT k2.id FROM kyc_cases k2 WHERE k2.customer_id=u.id ORDER BY k2.created_at DESC LIMIT 1) WHERE u.role='CUSTOMER' AND (?='' OR CONCAT_WS(' ',p.first_name,p.middle_name,p.last_name,u.email,p.mobile_number,p.customer_number,p.flexcube_customer_id) LIKE ?) AND (?='' OR u.kyc_status=?) AND (?='' OR p.risk_level=?) ORDER BY k.submitted_at DESC,u.created_at DESC LIMIT 100`,[input.query||"",query,input.status||"",input.status||"",input.riskLevel||"",input.riskLevel||""]);}
export async function getCustomerDetail(customerId:string){
  const rows=await pool.query<any[]>(`SELECT u.id,u.email,u.status AS digitalStatus,u.kyc_status AS kycStatus,u.created_at AS createdAt,u.last_login_at AS lastLoginAt,CONCAT_WS(' ',p.first_name,p.middle_name,p.last_name) AS name,p.*,p.mobile_number AS mobileNumber FROM users u JOIN customer_profiles p ON p.user_id=u.id WHERE u.id=? AND u.role='CUSTOMER'`,[customerId]);if(!rows[0])throw httpError(404,"Customer not found");const customer=rows[0];
  const cases=await pool.query<any[]>("SELECT id FROM kyc_cases WHERE customer_id=? ORDER BY created_at DESC LIMIT 1",[customerId]);const kycCase=cases[0]?await getOperationsKycCase(cases[0].id):null;
  const digitalTransactions=await pool.query<any[]>("SELECT id,correlation_id AS correlationId,transaction_type AS transactionType,source_account_id AS sourceAccountId,destination_account_number_masked AS destinationAccountNumberMasked,amount_minor AS amountMinor,currency,reference,status,provider_reference AS providerReference,created_at AS createdAt,completed_at AS completedAt FROM digital_transactions WHERE customer_id=? ORDER BY created_at DESC LIMIT 100",[customerId]);
  let coreCustomer=null,accounts:any[]=[];if(customer.flexcube_customer_id){coreCustomer=await coreBankingProvider.getCustomer(customer.flexcube_customer_id);accounts=await coreBankingProvider.getCustomerAccounts(customer.flexcube_customer_id);accounts=await Promise.all(accounts.map(async account=>({...account,balance:await coreBankingProvider.getBalance(account.id)})));}else accounts=await pool.query<any[]>("SELECT id,account_name AS accountName,account_type AS accountType,CONCAT('•••• ',RIGHT(account_number,4)) AS maskedAccountNumber,currency,balance_minor AS balanceMinor,status,provider FROM accounts WHERE user_id=?",[customerId]);return{customer,coreCustomer,accounts,kycCase,digitalTransactions};
}
export async function getOperationsKycCase(caseId:string){const base=await getKycCase(caseId),customerRows=await pool.query<any[]>(`SELECT u.email,u.status AS digitalStatus,u.kyc_status AS kycStatus,CONCAT_WS(' ',p.first_name,p.middle_name,p.last_name) AS name,p.flexcube_customer_id AS flexcubeCustomerId,p.customer_number AS customerNumber,p.mobile_number AS mobileNumber,p.mobile_verified AS mobileVerified,p.address_line1 AS address,p.city,p.postal_code AS postalCode,p.occupation,p.source_of_funds AS sourceOfFunds,p.politically_exposed AS politicallyExposed FROM users u JOIN customer_profiles p ON p.user_id=u.id WHERE u.id=?`,[base.customerId]);
 const [biometrics,screening,actions,audit]=await Promise.all([
  pool.query<any[]>("SELECT operation_type AS operationType,provider,provider_reference AS providerReference,trust_classification AS trustClassification,outcome,production_verified AS productionVerified,score,created_at AS createdAt,completed_at AS completedAt FROM biometric_operations WHERE customer_id=? ORDER BY created_at DESC",[base.customerId]),
  pool.query<any[]>("SELECT verification_type AS verificationType,provider,status,result_code AS resultCode,score,completed_at AS completedAt FROM kyc_verifications WHERE case_id=? AND verification_type IN ('SANCTIONS','PEP','ADVERSE_MEDIA') ORDER BY requested_at DESC",[caseId]),
  pool.query<any[]>(`SELECT a.id,a.action,a.status,a.notes,a.checker_notes AS checkerNotes,a.created_at AS createdAt,a.checked_at AS checkedAt,m.email AS maker,c.email AS checker FROM kyc_review_actions a JOIN users m ON m.id=a.maker_id LEFT JOIN users c ON c.id=a.checker_id WHERE a.case_id=? ORDER BY a.created_at DESC`,[caseId]),
  pool.query<any[]>(`SELECT e.id,e.action,e.entity_type AS entityType,e.entity_id AS entityId,e.metadata_json AS metadata,e.created_at AS createdAt,u.email AS actor FROM audit_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.entity_id IN (?,?) OR JSON_UNQUOTE(JSON_EXTRACT(e.metadata_json,'$.caseId'))=? ORDER BY e.created_at DESC LIMIT 250`,[caseId,base.customerId,caseId]),
 ]);const customer=customerRows[0];let accountRelationship:any[]=[];if(customer?.flexcubeCustomerId)accountRelationship=await coreBankingProvider.getCustomerAccounts(customer.flexcubeCustomerId);else accountRelationship=await pool.query<any[]>("SELECT id,account_name AS accountName,account_type AS accountType,CONCAT('•••• ',RIGHT(account_number,4)) AS maskedAccountNumber,currency,status,provider FROM accounts WHERE user_id=?",[base.customerId]);return{...base,customer,accountRelationship,biometrics,screening,reviewActions:actions,auditTrail:audit,makerCheckerEnabled:config.KYC_MAKER_CHECKER_ENABLED};}
export async function getKycDocumentContent(documentId:string){const rows=await pool.query<any[]>("SELECT file_reference,content_type,original_file_name FROM kyc_documents WHERE id=?",[documentId]);if(!rows[0])throw httpError(404,"KYC document not found");return{...(await objectStorageProvider.getObject(rows[0].file_reference)),fileName:rows[0].original_file_name};}
async function applyAction(connection:PoolConnection,caseRow:any,actorId:string,action:OperationsAction,notes?:string){if(action==="ESCALATE"){await connection.query("INSERT INTO kyc_status_history(case_id,from_status,to_status,changed_by,change_reason,change_source) VALUES(?,?,?,?,?,'OPERATIONS_ESCALATION')",[caseRow.id,caseRow.status,caseRow.status,actorId,notes]);return;}const status=action==="APPROVE"?"APPROVED":action==="REJECT"?"REJECTED":"MORE_INFORMATION_REQUIRED",decision=status;await connection.query("INSERT INTO kyc_reviews(id,case_id,reviewer_id,decision,review_notes,requested_information) VALUES(?,?,?,?,?,?)",[randomUUID(),caseRow.id,actorId,decision,notes||null,action==="REQUEST_MORE_INFORMATION"?notes||null:null]);await connection.query("UPDATE kyc_cases SET status=?,reviewed_by=?,review_notes=?,reviewed_at=NOW(3) WHERE id=?",[status,actorId,notes||null,caseRow.id]);await connection.query("INSERT INTO kyc_status_history(case_id,from_status,to_status,changed_by,change_reason,change_source) VALUES(?,?,?,?,?,'OPERATIONS_REVIEW')",[caseRow.id,caseRow.status,status,actorId,notes||action]);if(caseRow.legacy_application_id)await connection.query("UPDATE kyc_applications SET status=?,reviewer_id=?,decision_notes=?,reviewed_at=NOW() WHERE id=?",[status,actorId,notes||null,caseRow.legacy_application_id]);await connection.query("UPDATE users SET kyc_status=?,status=? WHERE id=?",[status,status==="APPROVED"?"ACTIVE":status==="REJECTED"?"BLOCKED":"PENDING",caseRow.customer_id]);if(status==="APPROVED")await connection.query("UPDATE customer_profiles SET kyc_level=CASE WHEN kyc_level='LEVEL_0' THEN 'LEVEL_1' ELSE kyc_level END WHERE user_id=?",[caseRow.customer_id]);}
export async function proposeReviewAction(caseId:string,makerId:string,action:OperationsAction,notes?:string){if(["REJECT","ESCALATE"].includes(action)&&!notes?.trim())throw httpError(400,"Reviewer notes are required for rejection and escalation");const actionId=randomUUID(),status=config.KYC_MAKER_CHECKER_ENABLED?"PENDING_CHECK":"APPLIED";await inTransaction(async connection=>{const cases=await connection.query<any[]>("SELECT * FROM kyc_cases WHERE id=? FOR UPDATE",[caseId]);if(!cases[0])throw httpError(404,"KYC case not found");if(!["PENDING_REVIEW","MORE_INFORMATION_REQUIRED","IN_PROGRESS"].includes(cases[0].status)&&action!=="ESCALATE")throw httpError(409,"This case is not available for review");if(config.KYC_MAKER_CHECKER_ENABLED){const pending=await connection.query<any[]>("SELECT id FROM kyc_review_actions WHERE case_id=? AND status='PENDING_CHECK' LIMIT 1 FOR UPDATE",[caseId]);if(pending[0])throw httpError(409,"This case already has a decision awaiting an independent checker");}await connection.query("INSERT INTO kyc_review_actions(id,case_id,action,status,maker_id,notes) VALUES(?,?,?,?,?,?)",[actionId,caseId,action,status,makerId,notes||null]);if(!config.KYC_MAKER_CHECKER_ENABLED)await applyAction(connection,cases[0],makerId,action,notes);});await recordAuditEvent(makerId,"kyc.review_action_created","kyc_review_action",actionId,{caseId,action,status});return{actionId,status,makerCheckerEnabled:config.KYC_MAKER_CHECKER_ENABLED};}
export async function checkReviewAction(actionId:string,checkerId:string,decision:"CONFIRM"|"DECLINE",notes?:string){const result=await inTransaction(async connection=>{const rows=await connection.query<any[]>("SELECT a.*,c.customer_id,c.status AS case_status,c.legacy_application_id FROM kyc_review_actions a JOIN kyc_cases c ON c.id=a.case_id WHERE a.id=? FOR UPDATE",[actionId]),action=rows[0];if(!action)throw httpError(404,"Review action not found");if(action.status!=="PENDING_CHECK")throw httpError(409,"This review action has already been checked");if(action.maker_id===checkerId)throw httpError(403,"Maker/checker control prevents you from checking your own action");if(decision==="CONFIRM"&&action.action!=="ESCALATE"&&!["PENDING_REVIEW","MORE_INFORMATION_REQUIRED","IN_PROGRESS"].includes(action.case_status))throw httpError(409,"The KYC case changed before this decision was checked");const status=decision==="CONFIRM"?"APPLIED":"DECLINED";await connection.query("UPDATE kyc_review_actions SET status=?,checker_id=?,checker_notes=?,checked_at=NOW(3) WHERE id=?",[status,checkerId,notes||null,actionId]);if(decision==="CONFIRM")await applyAction(connection,{id:action.case_id,customer_id:action.customer_id,status:action.case_status,legacy_application_id:action.legacy_application_id},checkerId,action.action,action.notes);return{caseId:action.case_id,status,action:action.action};});await recordAuditEvent(checkerId,`kyc.review_action_${decision.toLowerCase()}`,"kyc_review_action",actionId,result);return result;}
