import { randomUUID } from "node:crypto";
import type { Request } from "express";
import { pool } from "../../db.js";
import type { AuthRequest,Role } from "../../auth.js";
export type AuditResult="SUCCESS"|"FAILURE"|"DENIED"|"PENDING";
export interface AuditEventInput {eventType:string;actorUserId?:string|null;actorRole?:Role|null;customerId?:string|null;entityType:string;entityId?:string|null;ipAddress?:string|null;deviceId?:string|null;correlationId?:string|null;result?:AuditResult;metadata?:unknown;}
function clientIp(req:Request){return req.ip||req.socket.remoteAddress||null;}
export async function appendAuditEvent(event:AuditEventInput):Promise<string>{const eventId=randomUUID();let role=event.actorRole||null,customerId=event.customerId||null;if(event.actorUserId&&(!role||!customerId)){const rows=await pool.query<any[]>("SELECT role FROM users WHERE id=? LIMIT 1",[event.actorUserId]);role=role||(rows[0]?.role??null);if(!customerId&&role==="CUSTOMER")customerId=event.actorUserId;}await pool.query(`INSERT INTO audit_events(event_id,event_type,actor_user_id,actor_role,customer_id,action,entity_type,entity_id,ip_address,device_id,correlation_id,result,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[eventId,event.eventType,event.actorUserId||null,role,customerId,event.eventType,event.entityType,event.entityId||null,event.ipAddress||null,event.deviceId||null,event.correlationId||null,event.result||"SUCCESS",event.metadata==null?null:JSON.stringify(event.metadata)]);return eventId;}
export async function auditFromRequest(req:AuthRequest,event:Omit<AuditEventInput,"actorUserId"|"actorRole"|"ipAddress"|"correlationId">&{actorUserId?:string|null;actorRole?:Role|null}){const eventId=await appendAuditEvent({...event,actorUserId:event.actorUserId??req.auth?.id??null,actorRole:event.actorRole??req.auth?.role??null,ipAddress:clientIp(req),correlationId:req.id||null,deviceId:event.deviceId||req.header("x-device-id")?.slice(0,180)||null});if(event.eventType==="BENEFICIARY_CREATION"&&req.auth?.id){const{notifyCustomer}=await import("../notifications/notification.service.js");await notifyCustomer(req.auth.id,"BENEFICIARY_ADDED",{beneficiaryName:"New beneficiary"},["IN_APP"],event.entityType,event.entityId||undefined,req.id);}return eventId;}
/** Compatibility entry point. New HTTP handlers should use auditFromRequest. */
export async function recordAuditEvent(actor:string|null,action:string,entityType:string,entityId:string|null,metadata:unknown=null):Promise<void>{await appendAuditEvent({eventType:action,actorUserId:actor,entityType,entityId,metadata});if(action==="kyc.review_action_confirm"&&entityId&&(metadata as any)?.status==="APPLIED"){const rows=await pool.query<any[]>("SELECT c.customer_id,a.action,c.id AS case_id FROM kyc_review_actions a JOIN kyc_cases c ON c.id=a.case_id WHERE a.id=?",[entityId]),row=rows[0];if(row&&["APPROVE","REJECT","REQUEST_MORE_INFORMATION"].includes(row.action)){const{notifyCustomer}=await import("../notifications/notification.service.js"),template=row.action==="APPROVE"?"KYC_APPROVED":row.action==="REJECT"?"KYC_REJECTED":"KYC_MORE_INFORMATION";await notifyCustomer(row.customer_id,template,{},row.action==="APPROVE"?["SMS","IN_APP"]:["IN_APP"],"kyc_case",row.case_id);}}}
export interface AuditSearch {eventType?:string;actorUserId?:string;customerId?:string;entityType?:string;result?:string;correlationId?:string;from?:string;to?:string;page:number;pageSize:number;}
export async function searchAuditEvents(input:AuditSearch){const where:string[]=["1=1"],values:any[]=[];const add=(sql:string,value:unknown)=>{where.push(sql);values.push(value);};if(input.eventType)add("e.event_type=?",input.eventType);if(input.actorUserId)add("e.actor_user_id=?",input.actorUserId);if(input.customerId)add("e.customer_id=?",input.customerId);if(input.entityType)add("e.entity_type=?",input.entityType);if(input.result)add("e.result=?",input.result);if(input.correlationId)add("e.correlation_id=?",input.correlationId);if(input.from)add("e.created_at>=?",input.from);if(input.to)add("e.created_at<=?",input.to);const offset=(input.page-1)*input.pageSize;const count=await pool.query<any[]>(`SELECT COUNT(*) total FROM audit_events e WHERE ${where.join(" AND ")}`,values);const rows=await pool.query<any[]>(`SELECT e.event_id AS eventId,e.event_type AS eventType,e.actor_user_id AS actorUserId,e.actor_role AS actorRole,e.customer_id AS customerId,e.entity_type AS entityType,e.entity_id AS entityId,e.created_at AS timestamp,e.ip_address AS ipAddress,e.device_id AS deviceId,e.correlation_id AS correlationId,e.result,e.metadata_json AS metadata,u.email AS actorEmail FROM audit_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE ${where.join(" AND ")} ORDER BY e.created_at DESC,e.id DESC LIMIT ? OFFSET ?`,[...values,input.pageSize,offset]);return{items:rows,page:input.page,pageSize:input.pageSize,total:Number(count[0].total)};}
