"use client";

import { FormEvent, useMemo, useState } from "react";
import type { User } from "./AuthGate";

const usersKey="duranki-users-v1";
function readUsers():User[]{try{return JSON.parse(localStorage.getItem(usersKey)||"[]")}catch{return[]}}

export default function AdminPortal({onExit}:{onExit:()=>void}){
  const [authenticated,setAuthenticated]=useState(false),[error,setError]=useState(""),[users,setUsers]=useState<User[]>(()=>readUsers());
  const [filter,setFilter]=useState<"all"|User["kycStatus"]>("pending"),[selected,setSelected]=useState<User|null>(null),[search,setSearch]=useState("");
  const visible=useMemo(()=>users.filter(user=>(filter==="all"||user.kycStatus===filter)&&(`${user.name} ${user.email} ${user.idNumber}`).toLowerCase().includes(search.toLowerCase())),[users,filter,search]);
  const counts={pending:users.filter(u=>u.kycStatus==="pending").length,approved:users.filter(u=>u.kycStatus==="approved").length,rejected:users.filter(u=>u.kycStatus==="rejected").length};

  function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(form.get("email")==="admin@duranki.local"&&form.get("password")==="Admin123!"){setAuthenticated(true);setError("")}else setError("Staff email or password is incorrect.")}
  function review(status:"approved"|"rejected"){
    if(!selected)return; const note=status==="rejected"?"Please contact the compliance team to provide updated identity information.":"KYC checks completed and approved.";
    const next=users.map(user=>user.id===selected.id?{...user,kycStatus:status,reviewedAt:new Date().toISOString(),reviewNote:note}:user) as User[];
    localStorage.setItem(usersKey,JSON.stringify(next));setUsers(next);setSelected(null);
  }
  if(!authenticated)return <main className="staff-login"><header className="auth-masthead"><img src="/duranki-logo.png" alt="Duranki"/><button className="staff-link" onClick={onExit}>CUSTOMER BANKING</button></header><div className="auth-accent"/><section><div className="staff-login-copy"><p className="auth-kicker">DURANKI BANK OPERATIONS</p><h1>Client and compliance control centre.</h1><p>Review customers, verify KYC profiles and control access to online banking.</p></div><div className="staff-login-card"><p className="eyebrow">Restricted access</p><h2>Bank staff login</h2><form className="auth-form" onSubmit={login}><label>Staff email<input name="email" type="email" required placeholder="admin@duranki.local"/></label><label>Password<input name="password" type="password" required placeholder="Staff password"/></label>{error&&<p className="auth-error">{error}</p>}<button className="auth-primary">Log in to operations</button></form><div className="demo-credentials"><b>Local prototype access</b><span>admin@duranki.local</span><span>Admin123!</span></div></div></section></main>;

  return <main className="admin-shell"><aside className="admin-sidebar"><img src="/duranki-logo.png" alt="Duranki"/><p>BANK OPERATIONS</p><nav><button className="active">▦ Overview</button><button>◎ KYC review <b>{counts.pending}</b></button><button>◫ Customers</button><button>⇄ Transactions</button><button>! Compliance</button><button>⌁ Reports</button></nav><button className="admin-exit" onClick={onExit}>↪ Exit staff portal</button></aside><section className="admin-content"><header><div><p className="eyebrow">Operations dashboard</p><h1>Client onboarding</h1></div><div className="admin-user"><span>Compliance Officer</span><b>CO</b></div></header><section className="admin-stats"><article><span>Awaiting review</span><strong>{counts.pending}</strong><small>Requires a decision</small></article><article><span>Approved clients</span><strong>{counts.approved}</strong><small>Online banking enabled</small></article><article><span>Rejected profiles</span><strong>{counts.rejected}</strong><small>Requires remediation</small></article><article><span>Total clients</span><strong>{users.length}</strong><small>Customer information file</small></article></section><section className="admin-panel"><div className="admin-toolbar"><div><h2>KYC profiles</h2><p>Review and authorize new online-banking clients.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or ID" aria-label="Search clients"/></div><div className="admin-filters">{(["pending","all","approved","rejected"] as const).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item[0].toUpperCase()+item.slice(1)}{item==="pending"&&<b>{counts.pending}</b>}</button>)}</div><div className="client-table"><div className="client-row head"><span>Client</span><span>Submitted</span><span>Risk</span><span>Status</span><span></span></div>{visible.map(user=><button className="client-row" key={user.id} onClick={()=>setSelected(user)}><span><b>{user.name}</b><small>{user.email}</small></span><span>{user.submittedAt?new Date(user.submittedAt).toLocaleDateString("en-ZA"):"Earlier"}</span><span><i className={user.politicallyExposed?"risk high":"risk low"}>{user.politicallyExposed?"Enhanced":"Standard"}</i></span><span><i className={`status ${user.kycStatus}`}>{user.kycStatus}</i></span><span>→</span></button>)}{visible.length===0&&<div className="admin-empty">No client profiles match this view.</div>}</div></section></section>
  {selected&&<div className="review-backdrop" onMouseDown={()=>setSelected(null)}><aside className="review-drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">Customer information file</p><h2>{selected.name}</h2><span className={`status ${selected.kycStatus}`}>{selected.kycStatus}</span><div className="review-section"><h3>Identity</h3><dl><dt>ID or passport</dt><dd>{selected.idNumber}</dd><dt>Date of birth</dt><dd>{selected.dateOfBirth}</dd><dt>Mobile</dt><dd>{selected.phone}</dd><dt>Email</dt><dd>{selected.email}</dd></dl></div><div className="review-section"><h3>Address and profile</h3><dl><dt>Residential address</dt><dd>{selected.address}, {selected.city}, {selected.postalCode}</dd><dt>Occupation</dt><dd>{selected.occupation}</dd><dt>Source of funds</dt><dd>{selected.sourceOfFunds}</dd><dt>Tax resident</dt><dd>{selected.taxResident?"Yes":"No"}</dd><dt>Politically exposed</dt><dd>{selected.politicallyExposed?"Yes — enhanced review":"No"}</dd></dl></div><div className="review-checks"><span>✓ Identity details captured</span><span>✓ Customer declarations accepted</span><span>{selected.politicallyExposed?"! Enhanced due diligence required":"✓ Standard risk profile"}</span></div>{selected.kycStatus==="pending"?<div className="review-actions"><button onClick={()=>review("rejected")}>Reject / request changes</button><button onClick={()=>review("approved")}>Approve online banking</button></div>:<div className="reviewed-note">Reviewed {selected.reviewedAt?new Date(selected.reviewedAt).toLocaleString("en-ZA"):"previously"}</div>}</aside></div>}
  </main>;
}
