"use client";

import { FormEvent, useEffect, useState } from "react";
import Dashboard from "./Dashboard";
import AdminPortal from "./AdminPortal";
import DemoOverview from "./DemoOverview";

export type User = { id:string; name:string; email:string; phone:string; passwordHash:string; idNumber:string; dateOfBirth:string; address:string; city:string; postalCode:string; occupation:string; sourceOfFunds:string; taxResident:boolean; politicallyExposed:boolean; kycStatus:"pending"|"approved"|"rejected"; submittedAt?:string; reviewedAt?:string; reviewNote?:string };
type Draft = Partial<User> & { password?:string; confirmPassword?:string; consent?:boolean };
const usersKey = "duranki-users-v1", sessionKey = "duranki-session-v1", draftKey = "duranki-kyc-draft-v1";

async function hash(value:string) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return Array.from(new Uint8Array(digest)).map(byte => byte.toString(16).padStart(2,"0")).join("");
}
function storedUsers():User[] { try { return JSON.parse(localStorage.getItem(usersKey) || "[]"); } catch { return []; } }

export default function AuthGate() {
  const [ready,setReady]=useState(false), [user,setUser]=useState<User|null>(null);
  const [staffMode,setStaffMode]=useState(false);
  const [demoMode,setDemoMode]=useState(false);
  const [mode,setMode]=useState<"signin"|"signup">("signin"), [step,setStep]=useState(1), [error,setError]=useState("");
  const [draft,setDraft]=useState<Draft>({taxResident:true,politicallyExposed:false});
  useEffect(()=>{ const users=storedUsers(), session=localStorage.getItem(sessionKey); setUser(users.find(item=>item.id===session)||null); try { const saved=JSON.parse(localStorage.getItem(draftKey)||"null"); if(saved)setDraft(saved); } catch {} setReady(true); },[]);

  function update(field:keyof Draft,value:string|boolean){ const next={...draft,[field]:value}; setDraft(next); localStorage.setItem(draftKey,JSON.stringify({...next,password:"",confirmPassword:""})); setError(""); }
  function nextStep(e:FormEvent){ e.preventDefault();
    if(step===1){ if(!draft.name?.trim()||!draft.email?.trim()||!draft.phone?.trim())return setError("Complete all contact details."); if(!/^\S+@\S+\.\S+$/.test(draft.email))return setError("Enter a valid email address."); if((draft.password?.length||0)<8)return setError("Use at least 8 characters for your password."); if(draft.password!==draft.confirmPassword)return setError("Passwords do not match."); if(storedUsers().some(item=>item.email.toLowerCase()===draft.email?.toLowerCase()))return setError("An account with this email already exists."); }
    if(step===2&&(!draft.idNumber?.trim()||!draft.dateOfBirth))return setError("Provide your identity number and date of birth.");
    if(step===3&&(!draft.address?.trim()||!draft.city?.trim()||!draft.postalCode?.trim()||!draft.occupation?.trim()||!draft.sourceOfFunds))return setError("Complete all address and financial profile fields.");
    setStep(current=>Math.min(4,current+1));
  }
  async function completeSignup(e:FormEvent){ e.preventDefault(); if(!draft.consent)return setError("You must accept the declarations to continue.");
    const created:User={id:crypto.randomUUID(),name:draft.name!.trim(),email:draft.email!.trim().toLowerCase(),phone:draft.phone!.trim(),passwordHash:await hash(draft.password||""),idNumber:draft.idNumber!.trim(),dateOfBirth:draft.dateOfBirth!,address:draft.address!.trim(),city:draft.city!.trim(),postalCode:draft.postalCode!.trim(),occupation:draft.occupation!.trim(),sourceOfFunds:draft.sourceOfFunds!,taxResident:Boolean(draft.taxResident),politicallyExposed:Boolean(draft.politicallyExposed),kycStatus:"pending",submittedAt:new Date().toISOString()};
    localStorage.setItem(usersKey,JSON.stringify([...storedUsers(),created])); localStorage.setItem(sessionKey,created.id); localStorage.removeItem(draftKey); setUser(created);
  }
  async function signIn(e:FormEvent<HTMLFormElement>){ e.preventDefault(); const form=new FormData(e.currentTarget), email=String(form.get("email")||"").trim().toLowerCase(), passwordHash=await hash(String(form.get("password")||"")); const match=storedUsers().find(item=>item.email===email&&item.passwordHash===passwordHash); if(!match)return setError("Email or password is incorrect."); localStorage.setItem(sessionKey,match.id); setUser(match); }
  function signOut(){ localStorage.removeItem(sessionKey); setUser(null); setMode("signin"); setError(""); }
  function updateCustomer(changes:Partial<User>){ if(!user)return; const updated={...user,...changes}; localStorage.setItem(usersKey,JSON.stringify(storedUsers().map(item=>item.id===user.id?updated:item))); setUser(updated); }
  function leaveStaff(){ const session=localStorage.getItem(sessionKey); setUser(storedUsers().find(item=>item.id===session)||null); setStaffMode(false); }
  if(!ready)return <div className="auth-loading">Opening Duranki securely…</div>;
  if(demoMode)return <DemoOverview onCustomer={()=>setDemoMode(false)} onStaff={()=>{setDemoMode(false);setStaffMode(true)}}/>;
  if(staffMode)return <AdminPortal onExit={leaveStaff}/>;
  if(user?.kycStatus==="approved")return <Dashboard user={user} onSignOut={signOut} onUpdateUser={updateCustomer}/>;
  if(user)return <main className="approval-shell"><header className="auth-masthead"><img src="/duranki-logo.png" alt="Duranki"/><button className="staff-link" onClick={()=>setStaffMode(true)}>BANK STAFF</button></header><div className="auth-accent"/><section className="approval-card"><div className={`approval-symbol ${user.kycStatus}`}>{user.kycStatus==="pending"?"◷":"!"}</div><p className="eyebrow">KYC application</p><h1>{user.kycStatus==="pending"?"Your profile is under review":"We need more information"}</h1><p>{user.kycStatus==="pending"?"Your registration was received. A Duranki compliance officer must approve your KYC profile before online banking becomes available.":user.reviewNote||"Your application could not be approved. Please contact Duranki support to update your information."}</p><div className="approval-status"><span>Application submitted</span><b>Complete</b><span>Identity and compliance review</span><b>{user.kycStatus==="pending"?"In progress":"Action required"}</b><span>Online banking access</span><b>Locked</b></div><small>Reference: {user.id.slice(0,8).toUpperCase()}</small><div className="approval-actions"><button onClick={signOut}>Sign out</button><button onClick={()=>setStaffMode(true)}>Bank operations portal</button></div></section></main>;

  const titles=["Create your account","Verify your identity","Tell us about yourself","Review and submit"];
  const subtitles=["First, set up your secure sign-in details.","We need these details to confirm who you are.","This helps us meet KYC requirements and protect your account.","Confirm your information and submit it for verification."];
  return <main className="auth-shell">
    <header className="auth-masthead"><img src="/duranki-logo.png" alt="Duranki"/><div><span>Secure online banking</span><button className="outline-nav" onClick={()=>setDemoMode(true)}>DEMO OVERVIEW</button>{mode==="signup"&&<button onClick={()=>{setMode("signin");setError("")}}>SIGN IN</button>}<button onClick={()=>setStaffMode(true)}>BANK STAFF</button></div></header>
    <div className="auth-accent" />
    <div className="auth-body">
    <section className="auth-story"><div><p className="auth-kicker">WELCOME TO DURANKI BANKING</p><h1>One clear view of<br/>your financial life.</h1><p>Enjoy convenient online banking with secure verification and control from any device.</p><ul><li>See accounts, cards and balances at a glance</li><li>Pay, transfer and manage beneficiaries securely</li><li>Search transactions and track monthly spending</li><li>Manage your profile, security and account settings</li></ul></div><div className="trust-row"><span>◆ Secure by design</span><span>◉ Private on this device</span></div></section>
    <section className="auth-card-wrap"><div className="auth-card">
      {mode==="signin"?<><p className="eyebrow">Secure access</p><h2>Log in</h2><p className="auth-subtitle">Access your Duranki accounts and services.</p><form className="auth-form discovery-login" onSubmit={signIn}><label>Email address<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/><button type="button" className="field-help">Forgot email?</button></label><label>Password<input name="password" type="password" autoComplete="current-password" required placeholder="Your password"/><button type="button" className="field-help">Forgot password?</button></label>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="login-actions"><button type="button" className="auth-secondary">Cancel</button><button className="auth-primary">Log in</button></div></form><div className="app-approval"><span>▣</span><div><strong>Protected sign-in</strong><p>Production access will be confirmed through the Duranki mobile app or a secure one-time code.</p></div></div><p className="auth-switch">New to Duranki? <button onClick={()=>{setMode("signup");setError("")}}>Register as a new client</button></p></>:
      <><div className="auth-progress-head"><div><p className="eyebrow">Digital onboarding</p><h2>{titles[step-1]}</h2></div><b>{step} of 4</b></div><div className="auth-progress"><i style={{width:`${step*25}%`}}/></div><p className="auth-subtitle">{subtitles[step-1]}</p>
      <form className="auth-form" onSubmit={step===4?completeSignup:nextStep}>
        {step===1&&<><label>Full legal name<input value={draft.name||""} onChange={e=>update("name",e.target.value)} autoComplete="name" placeholder="As shown on your ID"/></label><div className="auth-fields"><label>Email<input value={draft.email||""} onChange={e=>update("email",e.target.value)} type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Mobile number<input value={draft.phone||""} onChange={e=>update("phone",e.target.value)} type="tel" autoComplete="tel" placeholder="+27 82 123 4567"/></label></div><div className="auth-fields"><label>Create password<input value={draft.password||""} onChange={e=>update("password",e.target.value)} type="password" autoComplete="new-password" placeholder="8+ characters"/></label><label>Confirm password<input value={draft.confirmPassword||""} onChange={e=>update("confirmPassword",e.target.value)} type="password" autoComplete="new-password" placeholder="Repeat password"/></label></div></>}
        {step===2&&<><div className="verification-note"><span>◎</span><div><strong>Identity verification</strong><p>Your details remain on this device in this prototype. Production onboarding should connect to an approved identity provider.</p></div></div><label>South African ID or passport number<input value={draft.idNumber||""} onChange={e=>update("idNumber",e.target.value)} autoComplete="off" placeholder="Enter your identity number"/></label><label>Date of birth<input value={draft.dateOfBirth||""} onChange={e=>update("dateOfBirth",e.target.value)} onInput={e=>update("dateOfBirth",e.currentTarget.value)} type="date"/></label></>}
        {step===3&&<><label>Residential address<input value={draft.address||""} onChange={e=>update("address",e.target.value)} autoComplete="street-address" placeholder="Street and suburb"/></label><div className="auth-fields"><label>City<input value={draft.city||""} onChange={e=>update("city",e.target.value)} autoComplete="address-level2"/></label><label>Postal code<input value={draft.postalCode||""} onChange={e=>update("postalCode",e.target.value)} autoComplete="postal-code"/></label></div><label>Occupation<input value={draft.occupation||""} onChange={e=>update("occupation",e.target.value)} placeholder="Your current occupation"/></label><label>Primary source of funds<select value={draft.sourceOfFunds||""} onChange={e=>update("sourceOfFunds",e.target.value)}><option value="">Select one</option><option>Salary</option><option>Business income</option><option>Investments</option><option>Pension</option><option>Other</option></select></label><label className="check-row"><input type="checkbox" checked={Boolean(draft.taxResident)} onChange={e=>update("taxResident",e.target.checked)}/> I am a South African tax resident</label><label className="check-row"><input type="checkbox" checked={Boolean(draft.politicallyExposed)} onChange={e=>update("politicallyExposed",e.target.checked)}/> I am a politically exposed person or related to one</label></>}
        {step===4&&<><div className="review-grid"><span>Name<b>{draft.name}</b></span><span>Contact<b>{draft.email}<br/>{draft.phone}</b></span><span>Identity<b>•••• {draft.idNumber?.slice(-4)}</b></span><span>Address<b>{draft.address}, {draft.city}</b></span><span>Occupation<b>{draft.occupation}</b></span><span>Source of funds<b>{draft.sourceOfFunds}</b></span></div><label className="check-row consent"><input type="checkbox" checked={Boolean(draft.consent)} onChange={e=>update("consent",e.target.checked)}/> I confirm these details are accurate and consent to identity, sanctions and KYC verification.</label></>}
        {error&&<p className="auth-error" role="alert">{error}</p>}<div className="auth-actions">{step>1&&<button type="button" className="auth-secondary" onClick={()=>{setStep(step-1);setError("")}}>Back</button>}<button className="auth-primary">{step===4?"Submit for verification":"Continue"}</button></div>
      </form><p className="auth-switch">Already have an account? <button onClick={()=>{setMode("signin");setError("")}}>Sign in</button></p></>}
    </div></section>
    </div>
  </main>;
}
