"use client";

export default function DemoOverview({onCustomer,onStaff}:{onCustomer:()=>void;onStaff:()=>void}){
  return <main className="demo-overview">
    <header className="demo-nav"><img src="/great-lakes-bank-logo.png" alt="Great Lakes Bank"/><nav><a href="#experience">Experience</a><a href="#operations">Operations</a><a href="#delivery">Delivery</a></nav><button onClick={onCustomer}>Launch demo</button></header>
    <section className="demo-hero"><div><p className="demo-label">DIGITAL BANKING DEMONSTRATION</p><h1>One platform.<br/><em>Two experiences.</em></h1><p>A complete demonstration of responsive customer banking and the bank operations workflow behind secure digital onboarding.</p><div className="demo-hero-actions"><button onClick={onCustomer}>Explore customer banking</button><button onClick={onStaff}>Open operations portal</button></div></div><div className="device-stage"><div className="browser-frame"><div className="browser-bar"><i/><i/><i/><span>online.greatlakesbank.bi</span></div><div className="browser-ui"><aside>G<br/>⌂<br/>▣<br/>⇄<br/>▰</aside><article><small>SECURE CUSTOMER BANKING</small><h3>Accounts at a glance</h3><div className="ui-card">Balances and activity <b>Protected</b></div><div className="ui-lines"><i/><i/><i/></div></article></div></div><div className="phone-frame"><span></span><small>SECURE BANKING</small><h3>Your accounts</h3><div className="mobile-card">GREAT LAKES BANK<br/>Protected access</div><div className="mobile-actions"><i>↗</i><i>⌁</i><i>＋</i></div></div></div></section>

    <section className="demo-section" id="experience"><div className="section-heading"><p className="demo-label">01 · CUSTOMER EXPERIENCE</p><h2>Online banking on web and mobile</h2><p>One responsive interface adapts from full desktop banking to a touch-friendly mobile experience.</p></div><div className="capability-grid"><article><b>01</b><h3>Digital onboarding</h3><p>Guided registration, identity capture, customer declarations and a clear KYC status journey.</p></article><article><b>02</b><h3>Everyday banking</h3><p>Account overview, balances, payments, beneficiaries, cards, transactions and spending insights.</p></article><article><b>03</b><h3>Connected accounts</h3><p>Mobile money, external bank accounts, wallets, savings and investments in one portfolio view.</p></article><article><b>04</b><h3>Responsive mobile</h3><p>Adaptive navigation, compact cards, touch targets and mobile-first account management.</p></article></div></section>

    <section className="operations-showcase" id="operations"><div><p className="demo-label">02 · BANK OPERATIONS</p><h2>From application to approved client.</h2><p>The customer cannot access online banking until a compliance officer reviews and approves the KYC profile.</p><ol><li><span>1</span><div><b>Customer submits</b><small>Identity and financial profile captured digitally</small></div></li><li><span>2</span><div><b>Compliance reviews</b><small>Risk, PEP and customer information checked</small></div></li><li><span>3</span><div><b>Decision recorded</b><small>Approve access or request remediation</small></div></li><li><span>4</span><div><b>Banking activated</b><small>Approved client can securely sign in</small></div></li></ol><button onClick={onStaff}>Demonstrate KYC approval →</button></div><div className="ops-preview"><header><span>KYC review workflow</span><b>Live operational data</b></header>{[["01","New application","Customer-submitted evidence"],["02","Identity review","Provider and compliance results"],["03","Decision","Audited approval controls"]].map(item=><div key={item[0]}><i>{item[0]}</i><span><b>{item[1]}</b><small>{item[2]}</small></span><em>API-backed</em><strong>→</strong></div>)}</div></section>

    <section className="delivery-section" id="delivery"><div className="section-heading"><p className="demo-label">03 · DELIVERY MODEL</p><h2>Hosting, residency and implementation</h2><p>Deployment is selected around regulatory, operational and integration requirements.</p></div><div className="delivery-grid"><article><span>☁</span><h3>Managed cloud</h3><p>Dedicated production environments with managed scaling, monitoring, backups and disaster recovery.</p><ul><li>Fastest implementation</li><li>High availability</li><li>Managed security operations</li></ul></article><article><span>⌂</span><h3>Private cloud or on-premises</h3><p>Deploy within the bank’s controlled infrastructure or approved sovereign-cloud environment.</p><ul><li>Maximum infrastructure control</li><li>Private network integration</li><li>Bank-managed operations option</li></ul></article><article><span>⇄</span><h3>Hybrid deployment</h3><p>Keep regulated banking data in-country while digital channels and edge services scale independently.</p><ul><li>Core-banking connectivity</li><li>Controlled data boundaries</li><li>Flexible modernization path</li></ul></article></div><div className="residency-band"><div><p className="demo-label">DATA RESIDENCY</p><h3>Residency is configurable by jurisdiction.</h3><p>Customer records, KYC documents, audit logs, encryption keys and backups can be restricted to an approved country or region. Final architecture is confirmed through regulatory and security assessment.</p></div><div><span>Primary data</span><b>Selected in-country region</b><span>Backups and DR</span><b>Approved paired location</b><span>Data in transit</span><b>TLS encrypted</b><span>Data at rest</span><b>Customer-managed keys available</b></div></div>

    <div className="timeline"><div className="section-heading"><p className="demo-label">INDICATIVE TIMELINE</p><h2>Production implementation in 24–36 weeks</h2><p>Timing depends on core-banking integration, regulatory approvals and product scope.</p></div><div className="timeline-track"><article><b>01</b><span>Weeks 1–4</span><h3>Discover & design</h3><p>Requirements, journeys, architecture and regulatory mapping.</p></article><article><b>02</b><span>Weeks 5–12</span><h3>Foundation</h3><p>CIM, accounts, identity, environments and integrations.</p></article><article><b>03</b><span>Weeks 13–22</span><h3>Build & integrate</h3><p>Channels, KYC, operations, payments and reporting.</p></article><article><b>04</b><span>Weeks 23–30</span><h3>Assure & pilot</h3><p>Security, UAT, migration rehearsals and controlled pilot.</p></article><article><b>05</b><span>Weeks 31–36</span><h3>Launch & stabilize</h3><p>Production rollout, monitoring, training and hypercare.</p></article></div></div></section>
    <footer className="demo-footer"><img src="/great-lakes-bank-logo.png" alt="Great Lakes Bank"/><div><h2>Ready to see the complete journey?</h2><p>Start with a new customer application, then approve it in bank operations.</p></div><button onClick={onCustomer}>Start demonstration</button></footer>
  </main>
}

