"use client";

import { FormEvent,useMemo,useState } from "react";
import { API_ORIGIN,api } from "./api";
import type { User } from "./AuthGate";

type IdentityMethod="NATIONAL_ID"|"PASSPORT"|"ALTERNATIVE_ID"|"BRANCH_ASSISTED";
type Draft={firstName:string;middleName:string;lastName:string;dateOfBirth:string;gender:string;nationality:string;email:string;phone:string;password:string;confirmPassword:string;address:string;city:string;postalCode:string;identityMethod:IdentityMethod;identityNumber:string;alternativeDescription:string;occupation:string;sourceOfFunds:string;taxResident:boolean;politicallyExposed:boolean;consentAccuracy:boolean;consentBiometrics:boolean;consentPrivacy:boolean};
type KycCase={caseId:string};
type Props={initialUser?:User;onSessionUser:(user:User)=>void;onComplete:(user:User)=>void;onCancel:()=>void};

const stages=["Welcome","Personal information","Contact details","Address","Identification","Documents","Selfie","Liveness","Fingerprint","Income & funds","Review","Consent","Submit","Status"];
const descriptions=["Let’s verify your identity securely.","Tell us who you are.","How can the bank contact you?","Confirm where you live.","Choose the identity evidence available to you.","Capture or upload supporting evidence.","Provide a clear customer image.","Connect to our secure liveness provider.","Use fingerprint only when your device and policy require it.","Help us understand the source of your funds.","Check every detail before continuing.","Review and accept the required declarations.","Send your completed case to Great Lakes Bank.","Your application is now with the bank."];

export default function KycOnboarding({initialUser,onSessionUser,onComplete,onCancel}:Props){
  const [step,setStep]=useState(1),[error,setError]=useState(""),[busy,setBusy]=useState(false),[user,setUser]=useState<User|null>(initialUser||null),[caseId,setCaseId]=useState(""),[identityFile,setIdentityFile]=useState<File|null>(null),[selfieFile,setSelfieFile]=useState<File|null>(null),[faceVerification,setFaceVerification]=useState(""),[livenessSession,setLivenessSession]=useState(""),[fingerprintSession,setFingerprintSession]=useState(""),[requestFingerprint,setRequestFingerprint]=useState(false);
  const [draft,setDraft]=useState<Draft>({firstName:initialUser?.firstName||"",middleName:initialUser?.middleName||"",lastName:initialUser?.lastName||"",dateOfBirth:initialUser?.dateOfBirth||"",gender:initialUser?.gender||"",nationality:initialUser?.nationality||"Burundian",email:initialUser?.email||"",phone:initialUser?.mobileNumber||initialUser?.phone||"",password:"",confirmPassword:"",address:initialUser?.address||"",city:initialUser?.city||"",postalCode:initialUser?.postalCode||"",identityMethod:"NATIONAL_ID",identityNumber:"",alternativeDescription:"",occupation:initialUser?.occupation||"",sourceOfFunds:initialUser?.sourceOfFunds||"",taxResident:initialUser?.taxResident??true,politicallyExposed:initialUser?.politicallyExposed??false,consentAccuracy:false,consentBiometrics:false,consentPrivacy:false});
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>{setDraft(current=>({...current,[key]:value}));setError("");};
  const identityLabel=useMemo(()=>({NATIONAL_ID:"National identity document",PASSPORT:"Passport",ALTERNATIVE_ID:"Alternative approved document",BRANCH_ASSISTED:"Branch-assisted verification"})[draft.identityMethod],[draft.identityMethod]);

  function validate(){if(step===2&&(!draft.firstName.trim()||!draft.lastName.trim()||!draft.dateOfBirth||!draft.nationality.trim()))return"Complete the required personal information.";if(step===3&&(!/^\S+@\S+\.\S+$/.test(draft.email)||draft.phone.trim().length<7||(!initialUser&&(draft.password.length<12||!/[a-z]/.test(draft.password)||!/[A-Z]/.test(draft.password)||!/[0-9]/.test(draft.password)||!/[^A-Za-z0-9]/.test(draft.password)||draft.password!==draft.confirmPassword))))return initialUser?"Enter a valid email address and mobile number.":"Use matching passwords of at least 12 characters with upper-case, lower-case, number and special characters.";if(step===4&&(!draft.address.trim()||!draft.city.trim()))return"Enter your residential address and city.";if(step===5&&draft.identityMethod!=="BRANCH_ASSISTED"&&draft.identityNumber.trim().length<4)return"Enter the document number for the selected identification method.";if(step===5&&draft.identityMethod==="ALTERNATIVE_ID"&&!draft.alternativeDescription.trim())return"Describe the alternative identity document.";if(step===6&&draft.identityMethod!=="BRANCH_ASSISTED"&&!identityFile)return"Capture or upload the selected identity document.";if(step===7&&!selfieFile)return"Capture or select a clear selfie image.";if(step===8&&!livenessSession)return"Start the secure liveness session before continuing.";if(step===9&&requestFingerprint&&!fingerprintSession)return"Start the fingerprint provider session or turn off fingerprint for this application.";if(step===10&&(!draft.occupation.trim()||!draft.sourceOfFunds))return"Complete your occupation and source of funds.";if(step===12&&(!draft.consentAccuracy||!draft.consentBiometrics||!draft.consentPrivacy))return"Accept all required declarations before submitting.";return"";}

  async function uploadDocument(targetCaseId:string,file:File,documentType:string){const query=new URLSearchParams({documentType,originalFileName:file.name});if(draft.identityNumber&&documentType!=="SELFIE")query.set("documentNumber",draft.identityNumber);const response=await fetch(`${API_ORIGIN}/api/kyc/cases/${targetCaseId}/documents?${query}`,{method:"POST",credentials:"include",headers:{"Content-Type":file.type,"X-CSRF-Protection":"1"},body:file});const body=await response.json().catch(()=>({message:"Document upload failed"}));if(!response.ok)throw new Error(body.message||"Document upload failed");}
  async function establishSecureProfile(){
    let activeUser=user;
    if(!activeUser){const result=await api<{user:User}>("/api/auth/register",{method:"POST",headers:{"X-Device-Name":"Onboarding web browser","X-Device-Platform":"web"},body:JSON.stringify({email:draft.email,password:draft.password,firstName:draft.firstName,middleName:draft.middleName||undefined,lastName:draft.lastName,phone:draft.phone,dateOfBirth:draft.dateOfBirth,gender:draft.gender||undefined,nationality:draft.nationality,identityType:draft.identityMethod==="NATIONAL_ID"?"NATIONAL_ID":draft.identityMethod==="PASSPORT"?"PASSPORT":"OTHER",identityNumber:draft.identityNumber||undefined,addressLine1:draft.address,city:draft.city,postalCode:draft.postalCode||undefined,taxResident:draft.taxResident,politicallyExposed:draft.politicallyExposed})});activeUser=result.user;setUser(result.user);onSessionUser(result.user);}
    const kyc=caseId?{caseId}:await api<KycCase>("/api/kyc/cases/me");setCaseId(kyc.caseId);
    if(identityFile)await uploadDocument(kyc.caseId,identityFile,draft.identityMethod==="NATIONAL_ID"?"NATIONAL_ID":draft.identityMethod==="PASSPORT"?"PASSPORT":"ALTERNATIVE_ID");
    if(selfieFile){await uploadDocument(kyc.caseId,selfieFile,"SELFIE");if(!faceVerification){const capture={captureReference:`kyc-selfie:${kyc.caseId}`,contentType:selfieFile.type},enrollment=await api<{providerReference:string}>("/api/biometrics/face/enrollments",{method:"POST",body:JSON.stringify(capture)}),verification=await api<{outcome:string}>("/api/biometrics/face/verifications",{method:"POST",body:JSON.stringify({...capture,enrollmentReference:enrollment.providerReference})});setFaceVerification(verification.outcome);}}
  }
  async function startBiometric(kind:"liveness"|"fingerprint"){setBusy(true);setError("");try{if(!caseId)await establishSecureProfile();const result=await api<{sessionId:string;status:"pending"}>(`/api/biometrics/${kind}/sessions`,{method:"POST"});if(kind==="liveness"){await api(`/api/biometrics/liveness/sessions/${result.sessionId}`);setLivenessSession(result.sessionId);}else setFingerprintSession(result.sessionId);}catch(reason){setError(reason instanceof Error?reason.message:"The biometric provider could not be reached.");}finally{setBusy(false);}}
  async function next(event:FormEvent){event.preventDefault();const issue=validate();if(issue){setError(issue);return;}setBusy(true);setError("");try{if(step===7)await establishSecureProfile();if(step===10&&user)await api("/api/me",{method:"PUT",body:JSON.stringify({name:`${draft.firstName} ${draft.lastName}`,phone:draft.phone,address:draft.address,city:draft.city,postalCode:draft.postalCode,occupation:draft.occupation,sourceOfFunds:draft.sourceOfFunds,taxResident:draft.taxResident,politicallyExposed:draft.politicallyExposed})});setStep(value=>Math.min(14,value+1));}catch(reason){setError(reason instanceof Error?reason.message:"This onboarding step could not be completed.");}finally{setBusy(false);}}
  async function submit(){setBusy(true);setError("");try{const submission=await api<{caseId:string;status:"PENDING_REVIEW"}>(`/api/kyc/cases/${caseId}/submit`,{method:"POST"});const completed={...user!,kycStatus:submission.status,occupation:draft.occupation,sourceOfFunds:draft.sourceOfFunds};setUser(completed);onSessionUser(completed);setStep(14);}catch(reason){setError(reason instanceof Error?reason.message:"Your KYC application could not be submitted.");}finally{setBusy(false);}}

  return <div className="kyc-journey"><div className="auth-progress-head"><div><p className="eyebrow">Secure digital onboarding</p><h2>{stages[step-1]}</h2></div><b>{step} of 14</b></div><div className="auth-progress" aria-label={`Onboarding progress ${step} of 14`}><i style={{width:`${step/14*100}%`}}/></div><p className="auth-subtitle">{descriptions[step-1]}</p><div className="kyc-stage-dots">{stages.map((name,index)=><i key={name} className={index+1===step?"current":index+1<step?"done":""} title={name}/>)}</div>
    {step===14?<section className="kyc-status-card"><span>✓</span><p className="eyebrow">KYC status</p><h3>Pending KYC review</h3><p>Your information and evidence were submitted securely. A Great Lakes Bank compliance officer will review your case.</p><dl><div><dt>Reference</dt><dd>{caseId.slice(0,8).toUpperCase()}</dd></div><div><dt>Status</dt><dd>PENDING REVIEW</dd></div><div><dt>Next step</dt><dd>Bank verification</dd></div></dl><button className="auth-primary" onClick={()=>onComplete(user!)}>View application status</button></section>:
    <form className="auth-form kyc-form" onSubmit={step===13?event=>{event.preventDefault();void submit();}:next}>
      {step===1&&<div className="kyc-intro"><span>◉</span><h3>Identity that works for everyone</h3><p>You can use a national identity document, passport, another approved document, or request branch-assisted verification. Not having a modern national ID does not automatically prevent onboarding.</p><ul><li>Your information is encrypted in transit</li><li>Biometric results come from the bank’s configured provider</li><li>A compliance officer makes the final decision</li></ul></div>}
      {step===2&&<><div className="auth-fields"><label>First name<input value={draft.firstName} onChange={e=>set("firstName",e.target.value)} autoComplete="given-name" required/></label><label>Middle name (optional)<input value={draft.middleName} onChange={e=>set("middleName",e.target.value)} autoComplete="additional-name"/></label></div><label>Surname<input value={draft.lastName} onChange={e=>set("lastName",e.target.value)} autoComplete="family-name" required/></label><div className="auth-fields"><label>Date of birth<input type="date" value={draft.dateOfBirth} onChange={e=>set("dateOfBirth",e.target.value)} required/></label><label>Gender<select value={draft.gender} onChange={e=>set("gender",e.target.value)}><option value="">Prefer not to say</option><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="NON_BINARY">Non-binary</option><option value="OTHER">Other</option></select></label></div><label>Nationality<input value={draft.nationality} onChange={e=>set("nationality",e.target.value)} required/></label></>}
      {step===3&&<><label>Email address<input type="email" value={draft.email} onChange={e=>set("email",e.target.value)} autoComplete="email" required readOnly={Boolean(initialUser)}/></label><label>Mobile number<input type="tel" value={draft.phone} onChange={e=>set("phone",e.target.value)} autoComplete="tel" placeholder="+257 …" required/></label>{initialUser?<div className="verification-note"><span>✓</span><div><strong>Secure access created</strong><p>Your password and transaction PIN were set during digital activation.</p></div></div>:<div className="auth-fields"><label>Create password<input type="password" minLength={12} value={draft.password} onChange={e=>set("password",e.target.value)} autoComplete="new-password" required/></label><label>Confirm password<input type="password" minLength={12} value={draft.confirmPassword} onChange={e=>set("confirmPassword",e.target.value)} autoComplete="new-password" required/></label></div>}</>}
      {step===4&&<><label>Residential address<input value={draft.address} onChange={e=>set("address",e.target.value)} autoComplete="street-address" required/></label><div className="auth-fields"><label>City / province<input value={draft.city} onChange={e=>set("city",e.target.value)} required/></label><label>Postal code (optional)<input value={draft.postalCode} onChange={e=>set("postalCode",e.target.value)}/></label></div><div className="verification-note"><span>⌂</span><div><strong>Address evidence</strong><p>The bank may request a utility bill, official letter, or branch confirmation depending on the applicable KYC policy.</p></div></div></>}
      {step===5&&<><div className="identity-options">{(["NATIONAL_ID","PASSPORT","ALTERNATIVE_ID","BRANCH_ASSISTED"] as IdentityMethod[]).map(method=><button type="button" key={method} className={draft.identityMethod===method?"selected":""} onClick={()=>set("identityMethod",method)}><b>{method==="NATIONAL_ID"?"▣":method==="PASSPORT"?"◫":method==="ALTERNATIVE_ID"?"◇":"⌂"}</b><span>{({NATIONAL_ID:"National ID",PASSPORT:"Passport",ALTERNATIVE_ID:"Other document",BRANCH_ASSISTED:"Branch assisted"})[method]}</span></button>)}</div>{draft.identityMethod!=="BRANCH_ASSISTED"&&<label>{identityLabel} number<input value={draft.identityNumber} onChange={e=>set("identityNumber",e.target.value)} required/></label>}{draft.identityMethod==="ALTERNATIVE_ID"&&<label>Document description<input value={draft.alternativeDescription} onChange={e=>set("alternativeDescription",e.target.value)} placeholder="For example voter card or approved civil record" required/></label>}{draft.identityMethod==="BRANCH_ASSISTED"&&<div className="verification-note"><span>⌂</span><div><strong>Branch-assisted path selected</strong><p>A bank employee can confirm available evidence during review. This selection does not automatically reject your application.</p></div></div>}</>}
      {step===6&&<div className="capture-card"><span>▤</span><h3>{draft.identityMethod==="BRANCH_ASSISTED"?"Add any evidence you have":"Upload your identity evidence"}</h3><p>PDF, JPEG or PNG. Files are sent to protected KYC document storage, not browser storage.</p><label className="file-button">Choose document<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setIdentityFile(e.target.files?.[0]||null)}/></label>{identityFile&&<b>{identityFile.name}</b>}</div>}
      {step===7&&<div className="capture-card"><span>◎</span><h3>Capture a clear selfie</h3><p>Use an evenly lit image with your full face visible. Selecting an image does not mark face verification as successful.</p><label className="file-button">Open camera or choose image<input type="file" accept="image/jpeg,image/png" capture="user" onChange={e=>setSelfieFile(e.target.files?.[0]||null)}/></label>{selfieFile&&<b>{selfieFile.name}</b>}</div>}
      {step===8&&<div className="biometric-card"><span>◉</span><h3>Liveness verification</h3><p>The web app requests a session from the bank’s biometric provider. Only that provider can return a verified result.</p>{livenessSession?<div className="provider-state"><i/>Provider session pending <small>{livenessSession.slice(0,8).toUpperCase()}</small></div>:<button type="button" className="auth-primary" disabled={busy} onClick={()=>void startBiometric("liveness")}>{busy?"Connecting…":"Start secure liveness session"}</button>}</div>}
      {step===9&&<div className="biometric-card"><span>◌</span><h3>Fingerprint verification</h3><p>Fingerprint is requested only when required by policy and supported by the customer’s registered device or branch equipment.</p><label className="check-row"><input type="checkbox" checked={requestFingerprint} onChange={e=>{setRequestFingerprint(e.target.checked);setFingerprintSession("")}}/> Fingerprint verification is required for my onboarding path</label>{requestFingerprint&&(fingerprintSession?<div className="provider-state"><i/>Provider session pending <small>{fingerprintSession.slice(0,8).toUpperCase()}</small></div>:<button type="button" className="auth-primary" disabled={busy} onClick={()=>void startBiometric("fingerprint")}>{busy?"Connecting…":"Connect fingerprint provider"}</button>)}</div>}
      {step===10&&<><label>Occupation / economic activity<input value={draft.occupation} onChange={e=>set("occupation",e.target.value)} required/></label><label>Primary source of income or funds<select value={draft.sourceOfFunds} onChange={e=>set("sourceOfFunds",e.target.value)} required><option value="">Select one</option><option>Salary</option><option>Business income</option><option>Agriculture</option><option>Investments</option><option>Pension</option><option>Family support</option><option>Other</option></select></label><label className="check-row"><input type="checkbox" checked={draft.taxResident} onChange={e=>set("taxResident",e.target.checked)}/> I am tax resident in my declared jurisdiction</label><label className="check-row"><input type="checkbox" checked={draft.politicallyExposed} onChange={e=>set("politicallyExposed",e.target.checked)}/> I am a politically exposed person or closely related to one</label></>}
      {step===11&&<div className="review-grid"><span>Name<b>{draft.firstName} {draft.middleName} {draft.lastName}</b></span><span>Contact<b>{draft.email}<br/>{draft.phone}</b></span><span>Address<b>{draft.address}<br/>{draft.city}</b></span><span>Identification<b>{identityLabel}<br/>{draft.identityNumber?`•••• ${draft.identityNumber.slice(-4)}`:"Branch review"}</b></span><span>Biometrics<b>Liveness: provider pending<br/>Fingerprint: {requestFingerprint?"provider pending":"not required"}</b></span><span>Funds<b>{draft.occupation}<br/>{draft.sourceOfFunds}</b></span></div>}
      {step===12&&<div className="consent-list"><label className="check-row consent"><input type="checkbox" checked={draft.consentAccuracy} onChange={e=>set("consentAccuracy",e.target.checked)}/> I confirm that the information and documents provided are accurate.</label><label className="check-row consent"><input type="checkbox" checked={draft.consentBiometrics} onChange={e=>set("consentBiometrics",e.target.checked)}/> I consent to biometric processing for identity and liveness verification.</label><label className="check-row consent"><input type="checkbox" checked={draft.consentPrivacy} onChange={e=>set("consentPrivacy",e.target.checked)}/> I consent to KYC, sanctions, risk and compliance checks under the bank’s privacy notice.</label></div>}
      {step===13&&<div className="submit-summary"><span>✓</span><h3>Ready for compliance review</h3><p>Submitting locks this onboarding version and sends the case to Great Lakes Bank Operations. Pending biometric sessions remain pending until the configured provider returns a result.</p><dl><div><dt>Identity path</dt><dd>{identityLabel}</dd></div><div><dt>Evidence</dt><dd>{identityFile?"Document attached":"Branch assisted"}</dd></div><div><dt>Biometrics</dt><dd>Provider-managed</dd></div></dl></div>}
      {error&&<p className="auth-error" role="alert">{error}</p>}<div className="auth-actions">{step===1?<button type="button" className="auth-secondary" onClick={onCancel}>Cancel</button>:<button type="button" className="auth-secondary" disabled={busy} onClick={()=>{setStep(value=>value-1);setError("")}}>Back</button>}<button className="auth-primary" disabled={busy}>{busy?"Please wait…":step===13?"Submit KYC application":step===1?"Begin verification":"Continue"}</button></div>
    </form>}
  </div>;
}
