import { randomUUID } from "node:crypto";
import type { CoreBankingBeneficiary,CoreBankingProvider,CoreBankingStatement,CoreBankingTransfer,CreateBeneficiaryRequest,CustomerSearch,StatementRequest,TransferRequest,UpdateBeneficiaryRequest } from "./core-banking-provider.js";
import { createMockFlexcubeData } from "./mock-flexcube-data.js";

/** In-memory development adapter. This is the sole access point for mock core-banking fixtures. */
export class MockFlexcubeAdapter implements CoreBankingProvider {
  private readonly data=createMockFlexcubeData();
  private transfers=new Map<string,CoreBankingTransfer>();
  private idempotency=new Map<string,CoreBankingTransfer>();

  async findCustomer(search:CustomerSearch){const accountCustomerId=search.accountNumber?this.data.accounts.find(a=>a.accountNumber===search.accountNumber)?.customerId:undefined;return structuredClone(this.data.customers.filter(c=>(!search.customerNumber||c.customerNumber===search.customerNumber)&&(!search.accountNumber||c.id===accountCustomerId)&&(!search.mobileNumber||c.mobileNumber===search.mobileNumber)&&(!search.email||c.email.toLowerCase()===search.email.toLowerCase())&&(!search.nationalId||c.nationalId===search.nationalId)));}
  async getCustomer(customerId:string){return structuredClone(this.data.customers.find(c=>c.id===customerId)||null);}
  async getCustomerAccounts(customerId:string){return structuredClone(this.data.accounts.filter(a=>a.customerId===customerId));}
  async getAccount(accountId:string){return structuredClone(this.data.accounts.find(a=>a.id===accountId)||null);}
  async getBalance(accountId:string){return structuredClone(this.data.balances[accountId]||null);}
  async getTransactionHistory(accountId:string){return structuredClone(this.data.transactions.filter(t=>t.accountId===accountId));}
  async getStatement(request:StatementRequest):Promise<CoreBankingStatement|null>{const account=this.data.accounts.find(a=>a.id===request.accountId);if(!account)return null;const history=this.data.transactions.filter(t=>t.accountId===request.accountId&&t.bookingDate>=request.fromDate&&t.bookingDate<=request.toDate),closing=this.data.balances[request.accountId]?.ledger||{amountMinor:0,currency:account.currency},movement=history.reduce((total,t)=>total+(t.type==="CREDIT"?t.amount.amountMinor:-t.amount.amountMinor),0);return structuredClone({account,period:{fromDate:request.fromDate,toDate:request.toDate},openingBalance:{amountMinor:closing.amountMinor-movement,currency:closing.currency},closingBalance:closing,transactions:history});}
  async getBeneficiaries(customerId:string){return structuredClone(this.data.beneficiaries.filter(b=>b.customerId===customerId));}
  async createBeneficiary(request:CreateBeneficiaryRequest){if(!this.data.customers.some(c=>c.id===request.customerId))throw Object.assign(new Error("Core banking customer not found"),{status:404});const beneficiary:CoreBankingBeneficiary={id:`FC-BEN-${randomUUID()}`,status:"ACTIVE",...request};this.data.beneficiaries.push(beneficiary);return structuredClone(beneficiary);}
  async verifyBeneficiary(customerId:string,beneficiaryId:string){const item=this.data.beneficiaries.find(b=>b.customerId===customerId&&b.id===beneficiaryId&&b.status!=="DISABLED");return structuredClone(item||null);}
  async updateBeneficiary(request:UpdateBeneficiaryRequest){const item=this.data.beneficiaries.find(b=>b.customerId===request.customerId&&b.id===request.beneficiaryId&&b.status!=="DISABLED");if(!item)return null;Object.assign(item,Object.fromEntries(Object.entries(request).filter(([key,value])=>!["customerId","beneficiaryId"].includes(key)&&value!==undefined)));return structuredClone(item);}
  async deactivateBeneficiary(customerId:string,beneficiaryId:string){const item=this.data.beneficiaries.find(b=>b.customerId===customerId&&b.id===beneficiaryId);if(!item)return null;item.status="DISABLED";return structuredClone(item);}
  async initiateTransfer(request:TransferRequest){const existing=this.idempotency.get(request.idempotencyKey);if(existing)return structuredClone(existing);const account=this.data.accounts.find(a=>a.id===request.debitAccountId&&a.customerId===request.customerId);if(!account)throw Object.assign(new Error("Debit account not found"),{status:404});if(account.currency!==request.amount.currency)throw Object.assign(new Error("Transfer currency does not match debit account"),{status:422});if(request.amount.amountMinor<=0)throw Object.assign(new Error("Transfer amount must be positive"),{status:422});const balance=this.data.balances[account.id];if(!balance||balance.available.amountMinor<request.amount.amountMinor)throw Object.assign(new Error("Insufficient available funds"),{status:422});const transfer:CoreBankingTransfer={transactionId:`FC-TXN-${randomUUID()}`,providerReference:`MOCK-FC-${Date.now()}`,status:"COMPLETED",submittedAt:new Date().toISOString()},bookingDate=transfer.submittedAt.slice(0,10);balance.available.amountMinor-=request.amount.amountMinor;balance.ledger.amountMinor-=request.amount.amountMinor;this.data.transactions.unshift({id:transfer.transactionId,accountId:account.id,bookingDate,valueDate:bookingDate,description:`Great Lakes Bank transfer · ${request.reference}`,reference:transfer.providerReference,type:"DEBIT",amount:structuredClone(request.amount),status:"COMPLETED"});const destination=this.data.accounts.find(item=>item.accountNumber===request.creditAccountNumber&&item.currency===request.amount.currency);if(destination){const destinationBalance=this.data.balances[destination.id];if(destinationBalance){destinationBalance.available.amountMinor+=request.amount.amountMinor;destinationBalance.ledger.amountMinor+=request.amount.amountMinor;}this.data.transactions.unshift({id:`${transfer.transactionId}-CR`,accountId:destination.id,bookingDate,valueDate:bookingDate,description:`Incoming Great Lakes Bank transfer · ${request.reference}`,reference:transfer.providerReference,type:"CREDIT",amount:structuredClone(request.amount),status:"COMPLETED"});}this.transfers.set(transfer.transactionId,transfer);this.idempotency.set(request.idempotencyKey,transfer);return structuredClone(transfer);}
  async getTransactionStatus(transactionId:string){return structuredClone(this.transfers.get(transactionId)||null);}
}
