import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { MockFaceVerificationProvider } from "../dist/integrations/biometric-provider/mock-face-verification-provider.js";
import { MockFingerprintProvider } from "../dist/integrations/biometric-provider/mock-fingerprint-provider.js";
import { MockLivenessProvider } from "../dist/integrations/biometric-provider/mock-liveness-provider.js";

test("mock biometric providers are unmistakably demo-only and never production verified",async()=>{const face=new MockFaceVerificationProvider(),liveness=new MockLivenessProvider(),fingerprint=new MockFingerprintProvider(),capture={captureReference:"object://temporary/capture"};for(const result of [await face.createEnrollment("customer",capture),await face.verifyFace("customer","enrollment",capture),await face.compareFaces("customer",capture,capture),await liveness.createSession("customer"),await fingerprint.enrollFingerprint("customer",capture),await fingerprint.verifyFingerprint("customer","enrollment",capture)]){assert.equal(result.trustClassification,"MOCK_DEMO_ONLY");assert.equal(result.productionVerified,false);assert.match(result.provider,/^MOCK_/);assert.match(result.metadata.warning,/DEMO RESULT ONLY/);}});

test("onboarding remains in progress until the authenticated customer submits",async()=>{const [registration,kycRoutes,kycService,biometricRoutes]=await Promise.all([readFile(new URL("../src/modules/authentication/authentication.routes.ts",import.meta.url),"utf8"),readFile(new URL("../src/modules/kyc/kyc.routes.ts",import.meta.url),"utf8"),readFile(new URL("../src/modules/kyc/kyc.service.ts",import.meta.url),"utf8"),readFile(new URL("../src/modules/biometrics/index.ts",import.meta.url),"utf8")]);assert.match(registration,/kycStatus:"IN_PROGRESS"/);assert.match(kycRoutes,/cases\/:caseId\/submit/);assert.match(kycService,/CUSTOMER_SUBMISSION/);assert.match(biometricRoutes,/router\.use\(requireAuth\)/);assert.doesNotMatch(biometricRoutes,/status[^\n]*PASSED/);});

test("pending customers can reach KYC and biometric routes before banking approval",async()=>{const [bankingRoutes,transactionRoutes]=await Promise.all([readFile(new URL("../src/modules/accounts/banking.routes.ts",import.meta.url),"utf8"),readFile(new URL("../src/modules/transactions/transaction.routes.ts",import.meta.url),"utf8")]);assert.doesNotMatch(bankingRoutes,/bankingRouter\.use\(requireAuth\s*,\s*requireApproved\)/);assert.match(bankingRoutes,/\/banking\/overview"\s*,\s*requireAuth\s*,\s*requireApproved/);assert.match(bankingRoutes,/\/cards\/freeze"\s*,\s*requireAuth\s*,\s*requireApproved/);assert.doesNotMatch(transactionRoutes,/transactionRouter\.use\(requireAuth\s*,\s*requireApproved\)/);assert.match(transactionRoutes,/\["\/transfers","\/transactions","\/payments","\/qr-requests"\]/);});
